apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: char-dot-net-auto-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: char-dot-net-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: char-dot-net-deploy
  labels:
    app: char-dot-net-deploy-label
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: char-dot-net
  template:
    metadata:
      labels:
        app: char-dot-net
    spec:
      containers:
        - name: char-dot-net
          image: arthn1/char-dot-net:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
