version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "P@55w0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      network-example:
        ipv4_address: 10.5.0.2
  chardotnet:
    image: char-dot-net
    depends_on:
      - sqlserver
    ports:
      - "5050:80"
    networks:
      network-example:
        ipv4_address: 10.5.0.3
networks:
  network-example:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
