apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 8080 # Porta que ser치 exposta para os usu치rios
      targetPort: 80 # Porta que o container est치 usando
  type: NodePort # LoadBalancer permite redirecionamento de tr치fego entre os pods
