apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 500Mi
  storageClassName: mysql
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/artur/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dbclaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mysql
  resources:
    requests:
      storage: 400Mi
