apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: mysql-service
spec:
  selector:
    # Selector for Pods
    app: mysql
  ports:
    # Port Map
    - port: 3306
      targetPort: 3306
  type: ClusterIP
