apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: asgard-service
spec:
  # type: LoadBalancer
  type: NodePort
  selector:
    # Selector for Pods
    app: asgard-deployment
  ports:
    # Port Map
    - port: 5050
      targetPort: 5050
