apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: char-dot-net-auto-scale-v5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: char-dot-net-deploy-v5
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
