apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: mssql-service
spec:
  selector:
    # Selector for Pods
    app: mssql-local
  ports:
    # Port Map
    - port: 1433
      targetPort: 1433
