apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-selector
  template:
    metadata:
      labels:
        app: mssql-selector
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: P@55w0rd
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "750m"
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-dbclaim
