# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert
#     kompose.version: 1.32.0 (HEAD)
#   labels:
#     io.kompose.service: sqlserver
#   name: sqlserver
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: sqlserver
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert
#         kompose.version: 1.32.0 (HEAD)
#       labels:
#         io.kompose.network/compose-network-example: "true"
#         io.kompose.service: sqlserver
#     spec:
#       containers:
#         - env:
#             - name: ACCEPT_EULA
#               value: "Y"
#             - name: SA_PASSWORD
#               value: P@55w0rd
#           image: mcr.microsoft.com/mssql/server
#           name: sqlserver
#           ports:
#             - containerPort: 1433
#               hostPort: 1433
#               protocol: TCP
#       restartPolicy: Always

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mssql-local-deploy
#   labels:
#     app: mssql-local-deploy-label
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mssql-local
#   template:
#     metadata:
#       labels:
#         app: mssql-local
#     spec:
#       containers:
#         - env:
#             - name: ACCEPT_EULA
#               value: "Y"
#             - name: SA_PASSWORD
#               value: P@55w0rd
#           image: mcr.microsoft.com/mssql/server
#           name: mssql-local
#           ports:
#             - containerPort: 1433
#               hostPort: 1433
#               protocol: TCP
#           volumesMounts:
#             - name: mssqldb
#               mountPath: /var/opt/mssql/data
#       volumes:
#         - name: mysql-persistent-storage
#           persistentVolumeClaim:
#             claimName: mysql-pv-claim
#       restartPolicy: Always

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-local-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-local
  template:
    metadata:
      labels:
        app: mssql-local
    spec:
      containers:
        - name: mssql-local
          image: mcr.microsoft.com/mssql/server
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: P@55w0rd
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "750m"
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: dbclaim
